import { Box } from "@chakra-ui/layout";
import { useMediaQuery } from "@chakra-ui/react";
import Head from "next/head";
import { Footer } from "./Footer";
import { Navbar } from "./Navbar";

/*
    Contains the navbar, wrapper component, and SEO tags.
    Use this to create a basic page layout.
*/

interface Props {
    children: React.ReactNode;
}

export const Layout: React.FC<Props> = ({ children }) => {
    const [isMobile] = useMediaQuery("(max-width: 768px)");

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <Box mt={8} mx="auto" maxW={isMobile ? "400px" : ""} w="100%">
                {children}
            </Box>
            <Footer />
        </>
    );
};
